/*
███████╗     ██╗███████╗    █████╗ ██╗   ██╗██████╗ ██╗ ██████╗
██╔════╝     ██║██╔════╝   ██╔══██╗██║   ██║██╔══██╗██║██╔═══██╗
███████╗     ██║█████╗     ███████║██║   ██║██║  ██║██║██║   ██║
╚════██║██   ██║██╔══╝     ██╔══██║██║   ██║██║  ██║██║██║   ██║
███████║╚█████╔╝██║███████╗██║  ██║╚██████╔╝██████╔╝██║╚██████╔╝
╚══════╝ ╚════╝ ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚═╝ ╚═════╝
*/

#pragma once
#include <JuceHeader.h>

namespace sjf::version_hints
{
    // The master map of known parameter IDs to their Version Hints
    // You can delete everything inside this map to regenerate the entire list
    inline static std::unordered_map<std::string, int> hints = {
        {"FXBypass", 1},
        {"FXOutGainGain", 1},
        {"FXLimiterBypass", 1},
        {"FXLimiterRel", 1},
        {"FXLimiterThr", 1},
        {"FXChainOSFilterType", 1},
        {"FXChainOSRatio", 1},
        {"FXChainMix", 1},
        {"FXChainBypass", 1},
        {"FXChainGateMix", 1},
        {"FXChainGateBypass", 1},
        {"FXChainGateRat", 1},
        {"FXChainGateThr", 1},
        {"FXChainGateRel", 1},
        {"FXChainGateAtt", 1},
        {"FXChainSpectMix", 1},
        {"FXChainSpectBypass", 1},
        {"FXChainSpectB16Solo", 1},
        {"FXChainSpectB16Mute", 1},
        {"FXChainSpectB16InG", 1},
        {"FXChainSpectB16DelMix", 1},
        {"FXChainSpectB16DelModDepth", 1},
        {"FXChainSpectB16DelModFreq", 1},
        {"FXChainSpectB16DelFeedback", 1},
        {"FXChainSpectB16DelLink", 1},
        {"FXChainSpectB16DelOffsetR", 1},
        {"FXChainSpectB16DelTimeR", 1},
        {"FXChainSpectB16DelOffsetL", 1},
        {"FXChainSpectB16DelTimeL", 1},
        {"FXChainSpectB16TremPhaseOffset", 1},
        {"FXChainSpectB16TremDepth", 1},
        {"FXChainSpectB16TremFreq", 1},
        {"FXChainSpectB15Solo", 1},
        {"FXChainSpectB15Mute", 1},
        {"FXChainSpectB15InG", 1},
        {"FXChainSpectB15DelMix", 1},
        {"FXChainSpectB15DelModDepth", 1},
        {"FXChainSpectB15DelModFreq", 1},
        {"FXChainSpectB15DelFeedback", 1},
        {"FXChainSpectB15DelLink", 1},
        {"FXChainSpectB15DelOffsetR", 1},
        {"FXChainSpectB15DelTimeR", 1},
        {"FXChainSpectB15DelOffsetL", 1},
        {"FXChainSpectB15DelTimeL", 1},
        {"FXChainSpectB15TremPhaseOffset", 1},
        {"FXChainSpectB15TremDepth", 1},
        {"FXChainSpectB15TremFreq", 1},
        {"FXChainSpectB14Solo", 1},
        {"FXChainSpectB14Mute", 1},
        {"FXChainSpectB14InG", 1},
        {"FXChainSpectB14DelMix", 1},
        {"FXChainSpectB14DelModDepth", 1},
        {"FXChainSpectB14DelModFreq", 1},
        {"FXChainSpectB14DelFeedback", 1},
        {"FXChainSpectB14DelLink", 1},
        {"FXChainSpectB14DelOffsetR", 1},
        {"FXChainSpectB14DelTimeR", 1},
        {"FXChainSpectB14DelOffsetL", 1},
        {"FXChainSpectB14DelTimeL", 1},
        {"FXChainSpectB14TremPhaseOffset", 1},
        {"FXChainSpectB14TremDepth", 1},
        {"FXChainSpectB14TremFreq", 1},
        {"FXChainSpectB13Solo", 1},
        {"FXChainSpectB13Mute", 1},
        {"FXChainSpectB13InG", 1},
        {"FXChainSpectB13DelMix", 1},
        {"FXChainSpectB13DelModDepth", 1},
        {"FXChainSpectB13DelModFreq", 1},
        {"FXChainSpectB13DelFeedback", 1},
        {"FXChainSpectB13DelLink", 1},
        {"FXChainSpectB13DelOffsetR", 1},
        {"FXChainSpectB13DelTimeR", 1},
        {"FXChainSpectB13DelOffsetL", 1},
        {"FXChainSpectB13DelTimeL", 1},
        {"FXChainSpectB13TremPhaseOffset", 1},
        {"FXChainSpectB13TremDepth", 1},
        {"FXChainSpectB13TremFreq", 1},
        {"FXChainSpectB12Solo", 1},
        {"FXChainSpectB12Mute", 1},
        {"FXChainSpectB12InG", 1},
        {"FXChainSpectB12DelMix", 1},
        {"FXChainSpectB12DelModDepth", 1},
        {"FXChainSpectB12DelModFreq", 1},
        {"FXChainSpectB12DelFeedback", 1},
        {"FXChainSpectB12DelLink", 1},
        {"FXChainSpectB12DelOffsetR", 1},
        {"FXChainSpectB12DelTimeR", 1},
        {"FXChainSpectB12DelOffsetL", 1},
        {"FXChainSpectB12DelTimeL", 1},
        {"FXChainSpectB12TremPhaseOffset", 1},
        {"FXChainSpectB12TremDepth", 1},
        {"FXChainSpectB12TremFreq", 1},
        {"FXChainSpectB11Solo", 1},
        {"FXChainSpectB11Mute", 1},
        {"FXChainSpectB11InG", 1},
        {"FXChainSpectB11DelMix", 1},
        {"FXChainSpectB11DelModDepth", 1},
        {"FXChainSpectB11DelModFreq", 1},
        {"FXChainSpectB11DelFeedback", 1},
        {"FXChainSpectB11DelLink", 1},
        {"FXChainSpectB11DelOffsetR", 1},
        {"FXChainSpectB11DelTimeR", 1},
        {"FXChainSpectB11DelOffsetL", 1},
        {"FXChainSpectB11DelTimeL", 1},
        {"FXChainSpectB11TremPhaseOffset", 1},
        {"FXChainSpectB11TremDepth", 1},
        {"FXChainSpectB11TremFreq", 1},
        {"FXChainSpectB10Solo", 1},
        {"FXChainSpectB10Mute", 1},
        {"FXChainSpectB10InG", 1},
        {"FXChainSpectB10DelMix", 1},
        {"FXChainSpectB10DelModDepth", 1},
        {"FXChainSpectB10DelModFreq", 1},
        {"FXChainSpectB10DelFeedback", 1},
        {"FXChainSpectB10DelLink", 1},
        {"FXChainSpectB10DelOffsetR", 1},
        {"FXChainSpectB10DelTimeR", 1},
        {"FXChainSpectB10DelOffsetL", 1},
        {"FXChainSpectB10DelTimeL", 1},
        {"FXChainSpectB10TremPhaseOffset", 1},
        {"FXChainSpectB10TremDepth", 1},
        {"FXChainSpectB10TremFreq", 1},
        {"FXChainSpectB9Solo", 1},
        {"FXChainSpectB9Mute", 1},
        {"FXChainSpectB9InG", 1},
        {"FXChainSpectB9DelMix", 1},
        {"FXChainSpectB9DelModDepth", 1},
        {"FXChainSpectB9DelModFreq", 1},
        {"FXChainSpectB9DelFeedback", 1},
        {"FXChainSpectB9DelLink", 1},
        {"FXChainSpectB9DelOffsetR", 1},
        {"FXChainSpectB9DelTimeR", 1},
        {"FXChainSpectB9DelOffsetL", 1},
        {"FXChainSpectB9DelTimeL", 1},
        {"FXChainSpectB9TremPhaseOffset", 1},
        {"FXChainSpectB9TremDepth", 1},
        {"FXChainSpectB9TremFreq", 1},
        {"FXChainSpectB8Solo", 1},
        {"FXChainSpectB8Mute", 1},
        {"FXChainSpectB8InG", 1},
        {"FXChainSpectB8DelMix", 1},
        {"FXChainSpectB8DelModDepth", 1},
        {"FXChainSpectB8DelModFreq", 1},
        {"FXChainSpectB8DelFeedback", 1},
        {"FXChainSpectB8DelLink", 1},
        {"FXChainSpectB8DelOffsetR", 1},
        {"FXChainSpectB8DelTimeR", 1},
        {"FXChainSpectB8DelOffsetL", 1},
        {"FXChainSpectB8DelTimeL", 1},
        {"FXChainSpectB8TremPhaseOffset", 1},
        {"FXChainSpectB8TremDepth", 1},
        {"FXChainSpectB8TremFreq", 1},
        {"FXChainSpectB7Solo", 1},
        {"FXChainSpectB7Mute", 1},
        {"FXChainSpectB7InG", 1},
        {"FXChainSpectB7DelMix", 1},
        {"FXChainSpectB7DelModDepth", 1},
        {"FXChainSpectB7DelModFreq", 1},
        {"FXChainSpectB7DelFeedback", 1},
        {"FXChainSpectB7DelLink", 1},
        {"FXChainSpectB7DelOffsetR", 1},
        {"FXChainSpectB7DelTimeR", 1},
        {"FXChainSpectB7DelOffsetL", 1},
        {"FXChainSpectB7DelTimeL", 1},
        {"FXChainSpectB7TremPhaseOffset", 1},
        {"FXChainSpectB7TremDepth", 1},
        {"FXChainSpectB7TremFreq", 1},
        {"FXChainSpectB6Solo", 1},
        {"FXChainSpectB6Mute", 1},
        {"FXChainSpectB6InG", 1},
        {"FXChainSpectB6DelMix", 1},
        {"FXChainSpectB6DelModDepth", 1},
        {"FXChainSpectB6DelModFreq", 1},
        {"FXChainSpectB6DelFeedback", 1},
        {"FXChainSpectB6DelLink", 1},
        {"FXChainSpectB6DelOffsetR", 1},
        {"FXChainSpectB6DelTimeR", 1},
        {"FXChainSpectB6DelOffsetL", 1},
        {"FXChainSpectB6DelTimeL", 1},
        {"FXChainSpectB6TremPhaseOffset", 1},
        {"FXChainSpectB6TremDepth", 1},
        {"FXChainSpectB6TremFreq", 1},
        {"FXChainSpectB5Solo", 1},
        {"FXChainSpectB5Mute", 1},
        {"FXChainSpectB5InG", 1},
        {"FXChainSpectB5DelMix", 1},
        {"FXChainSpectB5DelModDepth", 1},
        {"FXChainSpectB5DelModFreq", 1},
        {"FXChainSpectB5DelFeedback", 1},
        {"FXChainSpectB5DelLink", 1},
        {"FXChainSpectB5DelOffsetR", 1},
        {"FXChainSpectB5DelTimeR", 1},
        {"FXChainSpectB5DelOffsetL", 1},
        {"FXChainSpectB5DelTimeL", 1},
        {"FXChainSpectB5TremPhaseOffset", 1},
        {"FXChainSpectB5TremDepth", 1},
        {"FXChainSpectB5TremFreq", 1},
        {"FXChainSpectB4Solo", 1},
        {"FXChainSpectB4Mute", 1},
        {"FXChainSpectB4InG", 1},
        {"FXChainSpectB4DelMix", 1},
        {"FXChainSpectB4DelModDepth", 1},
        {"FXChainSpectB4DelModFreq", 1},
        {"FXChainSpectB4DelFeedback", 1},
        {"FXChainSpectB4DelLink", 1},
        {"FXChainSpectB4DelOffsetR", 1},
        {"FXChainSpectB4DelTimeR", 1},
        {"FXChainSpectB4DelOffsetL", 1},
        {"FXChainSpectB4DelTimeL", 1},
        {"FXChainSpectB4TremPhaseOffset", 1},
        {"FXChainSpectB4TremDepth", 1},
        {"FXChainSpectB4TremFreq", 1},
        {"FXChainSpectB3Solo", 1},
        {"FXChainSpectB3Mute", 1},
        {"FXChainSpectB3InG", 1},
        {"FXChainSpectB3DelMix", 1},
        {"FXChainSpectB3DelModDepth", 1},
        {"FXChainSpectB3DelModFreq", 1},
        {"FXChainSpectB3DelFeedback", 1},
        {"FXChainSpectB3DelLink", 1},
        {"FXChainSpectB3DelOffsetR", 1},
        {"FXChainSpectB3DelTimeR", 1},
        {"FXChainSpectB3DelOffsetL", 1},
        {"FXChainSpectB3DelTimeL", 1},
        {"FXChainSpectB3TremPhaseOffset", 1},
        {"FXChainSpectB3TremDepth", 1},
        {"FXChainSpectB3TremFreq", 1},
        {"FXChainSpectB2Solo", 1},
        {"FXChainSpectB2Mute", 1},
        {"FXChainSpectB2InG", 1},
        {"FXChainSpectB2DelMix", 1},
        {"FXChainSpectB2DelModDepth", 1},
        {"FXChainSpectB2DelModFreq", 1},
        {"FXChainSpectB2DelFeedback", 1},
        {"FXChainSpectB2DelLink", 1},
        {"FXChainSpectB2DelOffsetR", 1},
        {"FXChainSpectB2DelTimeR", 1},
        {"FXChainSpectB2DelOffsetL", 1},
        {"FXChainSpectB2DelTimeL", 1},
        {"FXChainSpectB2TremPhaseOffset", 1},
        {"FXChainSpectB2TremDepth", 1},
        {"FXChainSpectB2TremFreq", 1},
        {"FXChainSpectB1Solo", 1},
        {"FXChainSpectB1Mute", 1},
        {"FXChainSpectB1InG", 1},
        {"FXChainSpectB1DelMix", 1},
        {"FXChainSpectB1DelModDepth", 1},
        {"FXChainSpectB1DelModFreq", 1},
        {"FXChainSpectB1DelFeedback", 1},
        {"FXChainSpectB1DelLink", 1},
        {"FXChainSpectB1DelOffsetR", 1},
        {"FXChainSpectB1DelTimeR", 1},
        {"FXChainSpectB1DelOffsetL", 1},
        {"FXChainSpectB1DelTimeL", 1},
        {"FXChainSpectB1TremPhaseOffset", 1},
        {"FXChainSpectB1TremDepth", 1},
        {"FXChainSpectB1TremFreq", 1},
        {"FXChainSpectNumBands", 1},
        {"FXChainTremMix", 1},
        {"FXChainTremBypass", 1},
        {"FXChainTremPhaseOffset", 1},
        {"FXChainTremDepth", 1},
        {"FXChainTremFreq", 1},
        {"FXChainSpreadMix", 1},
        {"FXChainSpreadBypass", 1},
        {"FXChainSpreadOrder", 1},
        {"FXChainSpreadHighF", 1},
        {"FXChainSpreadLowF", 1},
        {"FXChainSpreadHigh", 1},
        {"FXChainSpreadLow", 1},
        {"FXChainReduxMix", 1},
        {"FXChainReduxBypass", 1},
        {"FXChainReduxBCMix", 1},
        {"FXChainReduxBCBypass", 1},
        {"FXChainReduxBCBits", 1},
        {"FXChainReduxDSMix", 1},
        {"FXChainReduxDSBypass", 1},
        {"OutputDummyOn", 1},
        {"OutputDummyCutoff", 1},
        {"InputDummyOn", 1},
        {"InputDummyCutoff", 1},
        {"FXChainReduxDSJitter", 1},
        {"FXChainReduxDSOutFilt8ve", 1},
        {"FXChainReduxDSOutFilt", 1},
        {"FXChainReduxDSInFilt", 1},
        {"FXChainReduxDSSR", 1},
        {"FXChainUtilMix", 1},
        {"FXChainUtilBypass", 1},
        {"FXChainUtilOutG", 1},
        {"FXChainUtilDC", 1},
        {"FXChainUtilBalance", 1},
        {"FXChainUtilMBOn", 1},
        {"FXChainUtilMBCutoff", 1},
        {"FXChainUtilSpread", 1},
        {"FXChainUtilMode", 1},
        {"FXChainUtilInRØ", 1},
        {"FXChainUtilInLØ", 1},
        {"FXChainAirMix", 1},
        {"FXChainAirBypass", 1},
        {"FXChainAirInG", 1},
        {"FXChainAirFilterCutoff", 1},
        {"Shape3rd", 1},
        {"Shape2nd", 1},
        {"FXChainAirShape", 1},
        {"FXChainAirAmount", 1},
        {"FXChainPhasMix", 1},
        {"FXChainPhasBypass", 1},
        {"FXChainPhasLFOInvert", 1},
        {"FXChainPhasLFOPhaseOffset", 1},
        {"FXChainPhasLFODepth", 1},
        {"FXChainPhasLFOWaveform", 1},
        {"FXChainPhasLFOFreqDiv", 1},
        {"FXChainPhasLFOFreqNumDivs", 1},
        {"FXChainPhasLFOFreqFreq", 1},
        {"FXChainPhasLFOFreqSync", 1},
        {"FXChainPhasOrder", 1},
        {"FXChainPhasFB", 1},
        {"FXChainPhasCentreF", 1},
        {"FXChainFlanMix", 1},
        {"FXChainFlanBypass", 1},
        {"FXChainFlanModInvert", 1},
        {"FXChainFlanModPhaseOffset", 1},
        {"FXChainFlanModDepth", 1},
        {"FXChainFlanModFreq", 1},
        {"FXChainFlanFeedback", 1},
        {"FXChainFlanLink", 1},
        {"FXChainFlanOffsetR", 1},
        {"FXChainFlanTimeR", 1},
        {"FXChainFlanOffsetL", 1},
        {"FXChainFlanTimeL", 1},
        {"FXChainChorMix", 1},
        {"FXChainChorBypass", 1},
        {"FXChainChorModInvert", 1},
        {"FXChainChorModPhaseOffset", 1},
        {"FXChainChorModDepth", 1},
        {"FXChainChorModFreq", 1},
        {"FXChainChorLink", 1},
        {"FXChainChorOffsetR", 1},
        {"FXChainChorTimeR", 1},
        {"FXChainChorOffsetL", 1},
        {"FXChainChorTimeL", 1},
        {"FXChainLaddMix", 1},
        {"FXChainLaddBypass", 1},
        {"FXChainLaddMode", 1},
        {"FXChainLaddDrive", 1},
        {"FXChainLaddResonance", 1},
        {"FXChainLaddCutoff", 1},
        {"FXChainFilt2Mix", 1},
        {"FXChainFilt2Bypass", 1},
        {"FXChainFilt2Type", 1},
        {"FXChainFilt2Q", 1},
        {"FXChainFilt2Cutoff", 1},
        {"FXChainFilt1Mix", 1},
        {"FXChainFilt1Bypass", 1},
        {"FXChainFilt1Type", 1},
        {"FXChainFilt1Q", 1},
        {"FXChainFilt1Cutoff", 1},
        {"FXChainCompMix", 1},
        {"FXChainCompBypass", 1},
        {"FXChainCompRel", 1},
        {"FXChainCompAtt", 1},
        {"FXChainCompRat", 1},
        {"FXChainCompThr", 1},
        {"FXChainRevMix", 1},
        {"FXChainRevBypass", 1},
        {"FXChainRevTankMix", 1},
        {"FXChainRevTankFreeWidth", 1},
        {"FXChainRevTankFreeDamp", 1},
        {"FXChainRevTankFreeSize", 1},
        {"delayTimesDelayTime23", 1},
        {"delayTimesDelayTime22", 1},
        {"delayTimesDelayTime21", 1},
        {"delayTimesDelayTime20", 1},
        {"delayTimesDelayTime19", 1},
        {"delayTimesDelayTime18", 1},
        {"delayTimesDelayTime17", 1},
        {"delayTimesDelayTime16", 1},
        {"delayTimesDelayTime15", 1},
        {"delayTimesDelayTime14", 1},
        {"delayTimesDelayTime13", 1},
        {"delayTimesDelayTime12", 1},
        {"delayTimesDelayTime11", 1},
        {"delayTimesDelayTime10", 1},
        {"delayTimesDelayTime9", 1},
        {"delayTimesDelayTime8", 1},
        {"delayTimesDelayTime7", 1},
        {"delayTimesDelayTime6", 1},
        {"delayTimesDelayTime5", 1},
        {"delayTimesDelayTime4", 1},
        {"delayTimesDelayTime3", 1},
        {"delayTimesDelayTime2", 1},
        {"delayTimesDelayTime1", 1},
        {"delayTimesDelayTime0", 1},
        {"FXChainRevTankRngModulation", 1},
        {"FXChainRevTankRngDiffusion", 1},
        {"FXChainRevTankRngDecay", 1},
        {"FXChainRevTankRngDamping", 1},
        {"FXChainRevTankRngSize", 1},
        {"FXChainRevTankType", 1},
        {"FXChainRevDiffMTTapsAmp127", 1},
        {"FXChainRevDiffMTTapsAmp126", 1},
        {"FXChainRevDiffMTTapsAmp125", 1},
        {"FXChainRevDiffMTTapsAmp124", 1},
        {"FXChainRevDiffMTTapsAmp123", 1},
        {"FXChainRevDiffMTTapsAmp122", 1},
        {"FXChainRevDiffMTTapsAmp121", 1},
        {"FXChainRevDiffMTTapsAmp120", 1},
        {"FXChainRevDiffMTTapsAmp119", 1},
        {"FXChainRevDiffMTTapsAmp118", 1},
        {"FXChainRevDiffMTTapsAmp117", 1},
        {"FXChainRevDiffMTTapsAmp116", 1},
        {"FXChainRevDiffMTTapsAmp115", 1},
        {"FXChainRevDiffMTTapsAmp114", 1},
        {"FXChainRevDiffMTTapsAmp113", 1},
        {"FXChainRevDiffMTTapsAmp112", 1},
        {"FXChainRevDiffMTTapsAmp111", 1},
        {"FXChainRevDiffMTTapsAmp110", 1},
        {"FXChainRevDiffMTTapsAmp109", 1},
        {"FXChainRevDiffMTTapsAmp108", 1},
        {"FXChainRevDiffMTTapsAmp107", 1},
        {"FXChainRevDiffMTTapsAmp106", 1},
        {"FXChainRevDiffMTTapsAmp105", 1},
        {"FXChainRevDiffMTTapsAmp104", 1},
        {"FXChainRevDiffMTTapsAmp103", 1},
        {"FXChainRevDiffMTTapsAmp102", 1},
        {"FXChainRevDiffMTTapsAmp101", 1},
        {"FXChainRevDiffMTTapsAmp100", 1},
        {"FXChainRevDiffMTTapsAmp99", 1},
        {"FXChainRevDiffMTTapsAmp98", 1},
        {"FXChainRevDiffMTTapsAmp97", 1},
        {"FXChainRevDiffMTTapsAmp96", 1},
        {"FXChainRevDiffMTTapsAmp95", 1},
        {"FXChainRevDiffMTTapsAmp94", 1},
        {"FXChainRevDiffMTTapsAmp93", 1},
        {"FXChainRevDiffMTTapsAmp92", 1},
        {"FXChainRevDiffMTTapsAmp91", 1},
        {"FXChainRevDiffMTTapsAmp90", 1},
        {"FXChainRevDiffMTTapsAmp89", 1},
        {"FXChainRevDiffMTTapsAmp88", 1},
        {"FXChainRevDiffMTTapsAmp87", 1},
        {"FXChainRevDiffMTTapsAmp86", 1},
        {"FXChainRevDiffMTTapsAmp85", 1},
        {"FXChainRevDiffMTTapsAmp84", 1},
        {"FXChainRevDiffMTTapsAmp83", 1},
        {"FXChainRevDiffMTTapsAmp82", 1},
        {"FXChainRevDiffMTTapsAmp81", 1},
        {"FXChainRevDiffMTTapsAmp80", 1},
        {"FXChainRevDiffMTTapsAmp79", 1},
        {"FXChainRevDiffMTTapsAmp78", 1},
        {"FXChainRevDiffMTTapsAmp77", 1},
        {"FXChainRevDiffMTTapsAmp76", 1},
        {"FXChainRevDiffMTTapsAmp75", 1},
        {"FXChainRevDiffMTTapsAmp74", 1},
        {"FXChainRevDiffMTTapsAmp73", 1},
        {"FXChainRevDiffMTTapsAmp72", 1},
        {"FXChainRevDiffMTTapsAmp71", 1},
        {"FXChainRevDiffMTTapsAmp70", 1},
        {"FXChainRevDiffMTTapsAmp69", 1},
        {"FXChainRevDiffMTTapsAmp68", 1},
        {"FXChainRevDiffMTTapsAmp67", 1},
        {"FXChainRevDiffMTTapsAmp66", 1},
        {"FXChainRevDiffMTTapsAmp65", 1},
        {"FXChainRevDiffMTTapsAmp64", 1},
        {"FXChainRevDiffMTTapsAmp63", 1},
        {"FXChainRevDiffMTTapsAmp62", 1},
        {"FXChainRevDiffMTTapsAmp61", 1},
        {"FXChainRevDiffMTTapsAmp60", 1},
        {"FXChainRevDiffMTTapsAmp59", 1},
        {"FXChainRevDiffMTTapsAmp58", 1},
        {"FXChainRevDiffMTTapsAmp57", 1},
        {"FXChainRevDiffMTTapsAmp56", 1},
        {"FXChainRevDiffMTTapsAmp55", 1},
        {"FXChainRevDiffMTTapsAmp54", 1},
        {"FXChainRevDiffMTTapsAmp53", 1},
        {"FXChainRevDiffMTTapsAmp52", 1},
        {"FXChainRevDiffMTTapsAmp51", 1},
        {"FXChainRevDiffMTTapsAmp50", 1},
        {"FXChainRevDiffMTTapsAmp49", 1},
        {"FXChainRevDiffMTTapsAmp48", 1},
        {"FXChainRevDiffMTTapsAmp47", 1},
        {"FXChainRevDiffMTTapsAmp46", 1},
        {"FXChainRevDiffMTTapsAmp45", 1},
        {"FXChainRevDiffMTTapsAmp44", 1},
        {"FXChainRevDiffMTTapsAmp43", 1},
        {"FXChainRevDiffMTTapsAmp42", 1},
        {"FXChainRevDiffMTTapsAmp41", 1},
        {"FXChainRevDiffMTTapsAmp40", 1},
        {"FXChainRevDiffMTTapsAmp39", 1},
        {"FXChainRevDiffMTTapsAmp38", 1},
        {"FXChainRevDiffMTTapsAmp37", 1},
        {"FXChainRevDiffMTTapsAmp36", 1},
        {"FXChainRevDiffMTTapsAmp35", 1},
        {"FXChainRevDiffMTTapsAmp34", 1},
        {"FXChainRevDiffMTTapsAmp33", 1},
        {"FXChainRevDiffMTTapsAmp32", 1},
        {"FXChainRevDiffMTTapsAmp31", 1},
        {"FXChainRevDiffMTTapsAmp30", 1},
        {"FXChainRevDiffMTTapsAmp29", 1},
        {"FXChainRevDiffMTTapsAmp28", 1},
        {"FXChainRevDiffMTTapsAmp27", 1},
        {"FXChainRevDiffMTTapsAmp26", 1},
        {"FXChainRevDiffMTTapsAmp25", 1},
        {"FXChainRevDiffMTTapsAmp24", 1},
        {"FXChainRevDiffMTTapsAmp23", 1},
        {"FXChainRevDiffMTTapsAmp22", 1},
        {"FXChainRevDiffMTTapsAmp21", 1},
        {"FXChainRevDiffMTTapsAmp20", 1},
        {"FXChainRevDiffMTTapsAmp19", 1},
        {"FXChainRevDiffMTTapsAmp18", 1},
        {"FXChainRevDiffMTTapsAmp17", 1},
        {"FXChainRevDiffMTTapsAmp16", 1},
        {"FXChainRevDiffMTTapsAmp15", 1},
        {"FXChainRevDiffMTTapsAmp14", 1},
        {"FXChainRevDiffMTTapsAmp13", 1},
        {"FXChainRevDiffMTTapsAmp12", 1},
        {"FXChainRevDiffMTTapsAmp11", 1},
        {"FXChainRevDiffMTTapsAmp10", 1},
        {"FXChainRevDiffMTTapsAmp9", 1},
        {"FXChainRevDiffMTTapsAmp8", 1},
        {"FXChainRevDiffMTTapsAmp7", 1},
        {"FXChainRevDiffMTTapsAmp6", 1},
        {"FXChainRevDiffMTTapsAmp5", 1},
        {"FXChainRevDiffMTTapsAmp4", 1},
        {"FXChainRevDiffMTTapsAmp3", 1},
        {"FXChainRevDiffMTTapsAmp2", 1},
        {"FXChainRevDiffMTTapsAmp1", 1},
        {"FXChainRevDiffMTTapsAmp0", 1},
        {"FXChainRevDiffMTDiff", 1},
        {"FXChainRevDiffType", 1},
        {"FXChainRevFiltCutoff", 1},
        {"FXChainRevPreDelTime", 1},
        {"FXChainDelMix", 1},
        {"FXChainDelBypass", 1},
        {"FXChainDelModInvert", 1},
        {"FXChainDelModPhaseOffset", 1},
        {"FXChainDelModDepth", 1},
        {"FXChainDelModWaveform", 1},
        {"FXChainDelModFreqDiv", 1},
        {"FXChainDelModFreqNumDivs", 1},
        {"FXChainDelModFreqFreq", 1},
        {"FXChainDelModFreqSync", 1},
        {"FXChainDelFiltBypass", 1},
        {"FXChainDelFiltCutoff", 1},
        {"FXChainDelDrive", 1},
        {"FXChainDelSaturationType", 1},
        {"FXChainDelSaturation", 1},
        {"FXChainDelFeedback", 1},
        {"FXChainDelPingPong", 1},
        {"FXChainDelLink", 1},
        {"FXChainDelDetuneR", 1},
        {"FXChainDelTimeROffset", 1},
        {"FXChainDelTimeRDivision", 1},
        {"FXChainDelTimeRNumDivisions", 1},
        {"FXChainDelTimeRTime", 1},
        {"FXChainDelTimeRSync", 1},
        {"FXChainDelDetuneL", 1},
        {"FXChainDelTimeLOffset", 1},
        {"FXChainDelTimeLDivision", 1},
        {"FXChainDelTimeLNumDivisions", 1},
        {"FXChainDelTimeLTime", 1},
        {"FXChainDelTimeLSync", 1},
        {"FXChainSatMix", 1},
        {"FXChainSatBypass", 1},
        {"FXChainSatPostFiltBypass", 1},
        {"FXChainSatPostFiltType", 1},
        {"FXChainSatPostFiltQ", 1},
        {"FXChainSatPostFiltCutoff", 1},
        {"FXChainSatWSOSFilterType", 1},
        {"FXChainSatWSOSRatio", 1},
        {"FXChainSatWSBias", 1},
        {"FXChainSatWSType", 1},
        {"FXChainSatWSDrive", 1},
        {"FXChainSatPreFiltBypass", 1},
        {"FXChainSatPreFiltType", 1},
        {"FXChainSatPreFiltQ", 1},
        {"FXChainSatPreFiltCutoff", 1},
        {"FXInGainGain", 1},
        {"FXModsLFO5Waveform", 1},
        {"FXModsLFO5FreqDiv", 1},
        {"FXModsLFO5FreqNumDivs", 1},
        {"FXModsLFO5FreqFreq", 1},
        {"FXModsLFO5FreqSync", 1},
        {"FXModsLFO4Waveform", 1},
        {"FXModsLFO4FreqDiv", 1},
        {"FXModsLFO4FreqNumDivs", 1},
        {"FXModsLFO4FreqFreq", 1},
        {"FXModsLFO4FreqSync", 1},
        {"FXModsLFO3Waveform", 1},
        {"FXModsLFO3FreqDiv", 1},
        {"FXModsLFO3FreqNumDivs", 1},
        {"FXModsLFO3FreqFreq", 1},
        {"FXModsLFO3FreqSync", 1},
        {"FXModsLFO2Waveform", 1},
        {"FXModsLFO2FreqDiv", 1},
        {"FXModsLFO2FreqNumDivs", 1},
        {"FXModsLFO2FreqFreq", 1},
        {"FXModsLFO2FreqSync", 1},
        {"FXModsLFO1Waveform", 1},
        {"FXModsLFO1FreqDiv", 1},
        {"FXModsLFO1FreqNumDivs", 1},
        {"FXModsLFO1FreqFreq", 1},
        {"FXModsLFO1FreqSync", 1},
        // Automatically populated at runtime during Debug builds
    };


    /**
     * @brief Retrieves the version hint for a parameter ID.
     * In Debug mode, if the parameter ID is not found, it updates this source file
     * on disk so the new parameter and its incremented hint are baked into the next build.
     */
    inline int getVersionHint(const juce::String& paramID)
    {
        const std::string idStr = paramID.toStdString();

        // 1. If it already exists in the map, return the saved hint
        if (auto it = hints.find(idStr); it != hints.end())
            return it->second;

        #if JUCE_DEBUG

        static const auto newVersionHint = [&](){
            int maxVersion = 0;
            for (const auto& [id, ver] : hints)
                maxVersion = std::max(maxVersion, ver);

            return maxVersion + 1;
        }();

        hints[idStr] = newVersionHint;

        const juce::File thisHeaderFile (__FILE__);

        if (thisHeaderFile.existsAsFile())
        {
            juce::String content = thisHeaderFile.loadFileAsString();

            // Locate the "hints = {" map block using regex/string searching
            const int mapStart = content.indexOf("hints = {");
            if (mapStart != -1)
            {
                const int insertPos = content.indexOf(mapStart, "\n") + 1;

                const juce::String entryToInsert = "        {\"" + paramID + "\", " + juce::String(newVersionHint) + "},\n";

                if (!content.contains("\"" + paramID + "\""))
                {
                    content = content.substring(0, insertPos) + entryToInsert + content.substring(insertPos);
                    ignoreUnused(thisHeaderFile.replaceWithText(content));

                    DBG("[VersionHints] Registered new parameter '" << paramID
                        << "' with Hint " << newVersionHint << " in " << thisHeaderFile.getFileName());
                }
            }
        }
        return newVersionHint;

        #endif

        return 0;
    }
}
